version: '3.7'

services:
  app:
    container_name: con_api-gateway
    build:
      context: ./
      dockerfile: app.dockerfile
    image: app_api_gateway:1.0
    ports:
      - "3000:3000"
      
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: